/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counterVote;
/**
 *
 * @author Ichsan
 */
public class CounterVote extends javax.swing.JApplet {

    /**
     * Initializes the applet CounterVote
     */
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CounterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CounterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CounterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CounterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        counterReset1 = new counterReset.CounterReset();
        counterReset2 = new counterReset.CounterReset();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(351, 184));
        setMinimumSize(new java.awt.Dimension(351, 184));
        setPreferredSize(new java.awt.Dimension(640, 360));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 107, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 229, 229));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/counterVote/assets/guiBtnJava.png"))); // NOI18N
        jButton1.setAutoscrolls(true);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 70, 60, 30);

        jButton2.setBackground(new java.awt.Color(68, 0, 206));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(229, 229, 229));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/counterVote/assets/guiBtnPHP.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed1(evt);
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 70, 60, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/counterVote/assets/guiBtnReset.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed2(evt);
                jButton3ActionPerformed1(evt);
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 90, 30, 30);

        counterReset1.setBackground(new java.awt.Color(242, 242, 242));
        counterReset1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        counterReset1.setForeground(new java.awt.Color(178, 90, 0));
        getContentPane().add(counterReset1);
        counterReset1.setBounds(60, 110, 60, 30);

        counterReset2.setBackground(new java.awt.Color(242, 242, 242));
        counterReset2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        counterReset2.setForeground(new java.awt.Color(127, 0, 255));
        getContentPane().add(counterReset2);
        counterReset2.setBounds(230, 110, 60, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/counterVote/assets/guiBG.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 351, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed2
        counterReset2.reset();
    }//GEN-LAST:event_jButton3ActionPerformed2

    private void jButton3ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed1
        counterReset1.reset();
    }//GEN-LAST:event_jButton3ActionPerformed1

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed1
        counterReset2.increment();
    }//GEN-LAST:event_jButton2ActionPerformed1

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        counterReset1.increment();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private counterReset.CounterReset counterReset1;
    private counterReset.CounterReset counterReset2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
